@echo off
echo Starting AI Business OS...

echo Starting Backend...
start "Backend" cmd /k "call venv\Scripts\activate && cd backend && uvicorn app.main:app --reload"

echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && npm start"

echo Servers are starting in new windows...
