"""add_cleaning_tables

Revision ID: a8b3bcec410c
Revises: 2dc9fbfe3677
Create Date: 2026-07-24 13:10:43.937080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b3bcec410c'
down_revision: Union[str, None] = '2dc9fbfe3677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_configs_id'), 'cleaning_configs', ['id'], unique=False)
    op.create_table('datasets_cleaned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_cleaned_id'), 'datasets_cleaned', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_cleaned_id'), table_name='datasets_cleaned')
    op.drop_table('datasets_cleaned')
    op.drop_index(op.f('ix_cleaning_configs_id'), table_name='cleaning_configs')
    op.drop_table('cleaning_configs')
    # ### end Alembic commands ###
